/// Flutter icons SaberIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SaberIcons
///      fonts:
///       - asset: fonts/SaberIcons.ttf
///
/// 
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class SaberIcons {
  SaberIcons._();

  static const _kFontFam = 'SaberIcons';
  static const String? _kFontPkg = null;

  static const IconData eraser = IconData(0xf12d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hand_pointer = IconData(0xf25a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pen = IconData(0xf304, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData highlighter = IconData(0xf591, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
