// This file is generated by the bump_version script.
// Run `./scripts/bump_version.dart --help` for more information.

/// The current app version as an ordinal number.
const buildNumber = 129050;

/// The current app version as a string.
const buildName = '1.29.5';

/// The year in which the current version was released.
const buildYear = 2026;
