// This file is generated by the apply_version script.
// Run `./scripts/apply_version.sh --help` for more information.

/// The current app version as an ordinal number.
const int buildNumber = 15020;

/// The current app version as a string.
const String buildName = '0.15.2';

/// The year in which the current version was released.
const int buildYear = 2023;
