name: saber # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '0.9.4' # just for humans, typically '1.2+git' or '1.3.2'
summary: A cross-platform libre handwritten notes app # 79 char long summary
description: |
  A cross-platform libre handwritten notes app, available for Android, iOS, Linux, Windows, and the web!
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
license: GPL-3.0+
compression: lzo
architectures:
  - build-on: amd64

slots:
  saber-svc:
    interface: dbus
    bus: session
    name: com.adilhanney.saber
parts:
  flutter-git:
    source: https://github.com/flutter/flutter.git
    source-tag: 3.7.0
    plugin: nil
    override-build: |
      set -eux
      mkdir -p $CRAFT_PART_INSTALL/usr/bin
      mkdir -p $CRAFT_PART_INSTALL/usr/libexec
      cp -r $CRAFT_PART_SRC $CRAFT_PART_INSTALL/usr/libexec/flutter
      ln -sf $CRAFT_PART_INSTALL/usr/libexec/flutter/bin/flutter $CRAFT_PART_INSTALL/usr/bin/flutter
      export PATH="$CRAFT_PART_INSTALL/usr/bin:$PATH"
      flutter doctor
    build-packages:
      - clang
      - cmake
      - curl
      - ninja-build
      - unzip
    override-prime: ''
  saber:
    # See 'snapcraft plugins'
    after: [flutter-git]
    plugin:  nil
    source: .
    source-tag: v${SNAPCRAFT_PROJECT_VERSION}
    build-packages:
      - libsecret-1-dev
      - libjsoncpp-dev
      - zenity
    stage-packages:
      - libjsoncpp25
      - libsecret-1-0
      - zenity
    override-build: |
      set -eux
      flutter pub get || true
      flutter build linux --release -v    
      mkdir -p $CRAFT_PART_INSTALL/bin
      cp -r build/linux/*/release/bundle/* $CRAFT_PART_INSTALL/bin/
  cleanup:
    after:  # Make this part run last; list all your other parts here
      - saber
      - flutter-git
    plugin: nil
    build-snaps:  # List all content-snaps and base snaps you're using here
      - core22
      - gnome-42-2204
      - gnome-42-2204-sdk
    override-prime: |
      set -eux
      for snap in "core22" "gnome-42-2204" "gnome-42-2204-sdk"; do  # List all content-snaps and base snaps you're using here
        cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$SNAPCRAFT_PRIME/{}" \;
      done
apps:
  saber:
    command: bin/saber
    extensions: [gnome]
    common-id: com.adilhanney.saber
    desktop: meta/gui/saber.desktop
    environment:
      HOME: $SNAP_REAL_HOME
    plugs:
      - home
      - network
    slots:
      - saber-svc
