name: saber # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
adopt-info: saber
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
license: GPL-3.0
compression: lzo
icon: assets/icon/icon.png
donation: https://github.com/sponsors/adil192
source-code: https://github.com/adil192/saber
issues: https://github.com/adil192/saber/issues
contact: soumyadeepghosh2004@zohomail.in
architectures:
  - build-on: amd64
  - build-on: arm64
  
parts:
  rustup:
    plugin: nil
    build-packages: [wget]
    build-environment:
      - RUSTUP_HOME: $CRAFT_PART_INSTALL/usr/share/rust
      - CARGO_HOME: $CRAFT_PART_INSTALL/usr/share/rust
      - CARGO_BUILD_JOBS: $CRAFT_PARALLEL_BUILD_COUNT
    override-pull: |
      wget https://sh.rustup.rs -O $CRAFT_PART_SRC/rustup-init.sh
      chmod +x $CRAFT_PART_SRC/rustup-init.sh
    override-build: |
      $CRAFT_PART_SRC/rustup-init.sh -y --no-modify-path
      mkdir -p $CRAFT_PART_INSTALL/usr/bin
      for i in `ls $RUSTUP_HOME/bin/`; do
        ln -s ../share/rust/bin/$i $CRAFT_PART_INSTALL/usr/bin/$i
      done
    override-prime: |
      echo 'Skip Prime'
  saber:
    after: [rustup]
    source: https://github.com/adil192/saber.git
    source-tag: 'v0.16.0'
    plugin: flutter
    #build-attributes: [enable-patchelf]
    build-packages:
      - curl
      - jq
      - libjsoncpp-dev
    build-snaps:
      - cmake
    stage-packages:
      - libjsoncpp25
      - zenity
    build-environment:
      - RUSTUP_HOME: $CRAFT_STAGE/usr/share/rust
      - CARGO_HOME: $CRAFT_STAGE/usr/share/rust
      - CARGO_BUILD_JOBS: $CRAFT_PARALLEL_BUILD_COUNT
    override-build: |
      craftctl default
      mkdir -p $CRAFT_PART_INSTALL/meta/gui
      mv $CRAFT_PART_SRC/flatpak/com.adilhanney.saber.desktop $CRAFT_PART_INSTALL/meta/gui/saber.desktop
      mkdir $CRAFT_PART_INSTALL/metainfo
      mv $CRAFT_PART_SRC/flatpak/com.adilhanney.saber.metainfo.xml $CRAFT_PART_INSTALL/metainfo/
    parse-info: [metainfo/com.adilhanney.saber.metainfo.xml]
  cleanup:
    after:  # Make this part run last; list all your other parts here
      - saber
      - rustup
    plugin: nil
    build-snaps:  # List all content-snaps and base snaps you're using here
      - core22
      - gnome-42-2204
      - gtk-common-themes
    override-prime: |
      set -eux
      for snap in "core22" "gnome-42-2204" "gtk-common-themes" ; do  # List all content-snaps and base snaps you're using here
        cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$SNAPCRAFT_PRIME/{}" \;
      done

apps:
  saber:
    command: saber
    desktop: meta/gui/saber.desktop
    extensions: [gnome]
    common-id: com.adilhanney.saber
    plugs:
      - home
      - network
      - network-status
