name: saber
version: 0.9.11
summary: Handwritten notes
description: A cross-platform libre handwritten notes app, available for Android, iOS, Linux, Windows, and macOS!

confinement: strict
base: core22
grade: devel

slots:
  dbus-saber:
    interface: dbus
    bus: session
    name: com.adilhanney.saber

apps:
  saber:
    command: saber
    extensions: [flutter-stable]
    plugs:
      - network
    slots:
      - dbus-saber

parts:
  saber:
    source: .
    plugin: flutter
    flutter-target: lib/main_snap.dart
    build-packages:
      - libsecret-1-dev
      - libjsoncpp-dev
    stage-packages:
      - libsecret-1-dev
      - libjsoncpp1-dev

