name: saber # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '0.9.4' # just for humans, typically '1.2+git' or '1.3.2'
summary: A cross-platform libre handwritten notes app # 79 char long summary
description: |
  A cross-platform libre handwritten notes app, available for Android, iOS, Linux, Windows, and the web!
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
license: GPL-3.0+
compression: lzo
architectures:
  - build-on: amd64

plugs:
  saber-svc:
    bus: session
    interface: dbus
    name: com.adilhanney.saber
parts:
  saber:
    # See 'snapcraft plugins'
    plugin:  flutter
    source: .
    source-tag: v${SNAPCRAFT_PROJECT_VERSION}
    build-packages:
      - libsecret-1-dev
      - libjsoncpp-dev
      - zenity
    stage-packages:
      - libjsoncpp1
      - libsecret-1-0
      - zenity
  cleanup:
    after:  # Make this part run last; list all your other parts here
      - saber
    plugin: nil
    build-snaps:  # List all content-snaps and base snaps you're using here
      - core18
      - gnome-3-28-1804
    override-prime: |
      set -eux
      for snap in "core18" "gnome-3-28-1804" ; do  # List all content-snaps and base snaps you're using here
        cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$SNAPCRAFT_PRIME/{}" \;
      done
apps:
  saber:
    command: bin/saber
    extensions: [gnome]
    common-id: com.adilhanney.saber
    desktop: meta/gui/saber.desktop
    environment:
      HOME: $SNAP_REAL_HOME
    plugs:
      - home
      - network
      - saber-svc
