name: Run secondary tests (coverage, onyxsdk)

on:
  # Enable manual run
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - "lib/i18n/**"
  push:
    paths-ignore:
      - "lib/i18n/**"

env:
  project-id: com.adilhanney.saber

jobs:
  run-tests:
    name: Run Flutter tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Remove unneeded files
        run: |
          rm -rf assets_raw
          rm -rf submodules

      - name: Install Flutter dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libx11-dev pkg-config cmake ninja-build libblkid-dev libsecret-1-dev libjsoncpp-dev

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - run: flutter pub get

      - name: Upload to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: coverage/lcov.info

      - name: Run tests (packages/onyxsdk_pen)
        working-directory: packages/onyxsdk_pen
        run: flutter test --reporter expanded
